language: node_js
node_js:
  - "node"
  - "lts/*"

install:
    - yarn

script: 'true'

cache:
  directories:
    - "node_modules"

after_success:
  - yarn build
  - echo "torch.njs.app" > build/CNAME

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  target_branch: gh-pages
  email: jiduye@gmail.com
  local-dir: build
  name: Travis Automatically Bot
  on:
    branch: master
